name: Flutter CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image:  cirrusci/flutter:v1.7.8-hotfix.4
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo flutter packages get
    - name: Run tests
      run: flutter test
